export default [
  {
    id: '1',
    author: 'author_1',
    name: 'name_1',
    nameEn: 'nameEn_1',
    description: 'description_1',
    status: "NEW",
  },
  {
    id: '2',
    author: 'author_2',
    name: 'name_2',
    nameEn: 'nameEn_2',
    description: 'description_2',
    status: "SEQUENCED",
  },
  {
    id: '3',
    author: 'author_3',
    name: 'name_3',
    nameEn: 'nameEn_3',
    description: 'description_3',
    status: "ASSIGNED",
  },
  {
    id: '4',
    author: 'author_4',
    name: 'name_4',
    nameEn: 'nameEn_4',
    description: 'description_4',
    status: "INPROGRESS",
  },
  {
    id: '5',
    author: 'author_5',
    name: 'name_5',
    nameEn: 'nameEn_5',
    description: 'description_5',
    status: "REMARKS",
  },
  {
    id: '6',
    author: 'author_6',
    name: 'name_6',
    nameEn: 'nameEn_6',
    description: 'description_6',
    status: "REMARKS",
  },
  {
    id: '7',
    author: 'author_7',
    name: 'name_7',
    nameEn: 'nameEn_7',
    description: 'description_7',
    status: "DONE",
  },
  {
    id: '8',
    author: 'author_8',
    name: 'name_8',
    nameEn: 'nameEn_8',
    description: 'description_8',
    status: "CANCELLED",
  },
  {
    id: '9',
    author: 'author_9',
    name: 'name_9',
    nameEn: 'nameEn_9',
    description: 'description_9',
    status: "INPROGRESS",
  },
  {
    id: '10',
    author: 'author_10',
    name: 'name_10',
    nameEn: 'nameEn_10',
    description: 'description_10',
    status: "INPROGRESS",
  },
  {
    id: '11',
    author: 'author_11',
    name: 'name_11',
    nameEn: 'nameEn_11',
    description: 'description_11',
    status: "INPROGRESS",
  },
  {
    id: '12',
    author: 'author_12',
    name: 'name_12',
    nameEn: 'nameEn_12',
    description: 'description_12',
    status: "INPROGRESS",
  },
  {
    id: '13',
    author: 'author_13',
    name: 'name_13',
    nameEn: 'nameEn_13',
    description: 'description_13',
    status: "INPROGRESS",
  },
  {
    id: '14',
    author: 'author_14',
    name: 'name_14',
    nameEn: 'nameEn_14',
    description: 'description_14',
    status: "INPROGRESS",
  },
  {
    id: '15',
    author: 'author_15',
    name: 'name_15',
    nameEn: 'nameEn_15',
    description: 'description_15',
    status: "INPROGRESS",
  },
  {
    id: '16',
    author: 'author_16',
    name: 'name_16',
    nameEn: 'nameEn_16',
    description: 'description_16',
    status: "INPROGRESS",
  },
  {
    id: '17',
    author: 'author_17',
    name: 'name_17',
    nameEn: 'nameEn_17',
    description: 'description_17',
    status: "INPROGRESS",
  },
  {
    id: '18',
    author: 'author_18',
    name: 'name_18',
    nameEn: 'nameEn_18',
    description: 'description_18',
    status: "INPROGRESS",
  },
  {
    id: '19',
    author: 'author_19',
    name: 'name_19',
    nameEn: 'nameEn_19',
    description: 'description_19',
    status: "INPROGRESS",
  },
  {
    id: '20',
    author: 'author_20',
    name: 'name_20',
    nameEn: 'nameEn_20',
    description: 'description_20',
    status: "INPROGRESS",
  },
  {
    id: '21',
    author: 'author_21',
    name: 'name_21',
    nameEn: 'nameEn_21',
    description: 'description_21',
    status: "INPROGRESS",
  },
  {
    id: '22',
    author: 'author_22',
    name: 'name_22',
    nameEn: 'nameEn_22',
    description: 'description_22',
    status: "INPROGRESS",
  },
{
    id: '23',
    author: 'author_23',
    name: 'name_23',
    nameEn: 'nameEn_23',
    description: 'description_23',
    status: "INPROGRESS",
  },
  {
    id: '24',
    author: 'author_24',
    name: 'name_24',
    nameEn: 'nameEn_24',
    description: 'description_24',
    status: "INPROGRESS",
  },
  {
    id: '25',
    author: 'author_25',
    name: 'name_25',
    nameEn: 'nameEn_25',
    description: 'description_25',
    status: "INPROGRESS",
  },
  {
    id: '26',
    author: 'author_26',
    name: 'name_26',
    nameEn: 'nameEn_26',
    description: 'description_26',
    status: "INPROGRESS",
  },
  {
    id: '27',
    author: 'author_27',
    name: 'name_27',
    nameEn: 'nameEn_27',
    description: 'description_27',
    status: "INPROGRESS",
  },
  {
    id: '28',
    author: 'author_28',
    name: 'name_28',
    nameEn: 'nameEn_28',
    description: 'description_28',
    status: "INPROGRESS",
  },
  {
    id: '29',
    author: 'author_29',
    name: 'name_29',
    nameEn: 'nameEn_29',
    description: 'description_29',
    status: "INPROGRESS",
  },
  {
    id: '30',
    author: 'author_30',
    name: 'name_30',
    nameEn: 'nameEn_30',
    description: 'description_30',
    status: "INPROGRESS",
  },
  {
    id: '31',
    author: 'author_31',
    name: 'name_31',
    nameEn: 'nameEn_31',
    description: 'description_31',
    status: "INPROGRESS",
  },
  {
    id: '32',
    author: 'author_32',
    name: 'name_32',
    nameEn: 'nameEn_32',
    description: 'description_32',
    status: "INPROGRESS",
  },
  {
    id: '33',
    author: 'author_33',
    name: 'name_33',
    nameEn: 'nameEn_33',
    description: 'description_33',
    status: "INPROGRESS",
  },
  {
    id: '34',
    author: 'author_34',
    name: 'name_34',
    nameEn: 'nameEn_34',
    description: 'description_34',
    status: "INPROGRESS",
  },
  {
    id: '35',
    author: 'author_35',
    name: 'name_35',
    nameEn: 'nameEn_35',
    description: 'description_35',
    status: "INPROGRESS",
  },
  {
    id: '36',
    author: 'author_36',
    name: 'name_36',
    nameEn: 'nameEn_36',
    description: 'description_36',
    status: "INPROGRESS",
  },
  {
    id: '37',
    author: 'author_37',
    name: 'name_37',
    nameEn: 'nameEn_37',
    description: 'description_37',
    status: "INPROGRESS",
  },
  {
    id: '38',
    author: 'author_38',
    name: 'name_38',
    nameEn: 'nameEn_38',
    description: 'description_38',
    status: "INPROGRESS",
  },
  {
    id: '39',
    author: 'author_39',
    name: 'name_39',
    nameEn: 'nameEn_39',
    description: 'description_39',
    status: "INPROGRESS",
  },
  ];
